export {default as Text} from "./text/text"
export {default as Icon} from "./icon/icon"
export {default as Button} from "./button/Button"
export {default as Input} from "./input/Input"
export {default as TextArea} from "./textArea/TextArea"
export {default as Switch} from "./switch/Switch"
